apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-mysql-deployment
spec:
  selector:
    matchLabels:
      app: docker-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-mysql
    spec:
      containers:
        - name: docker-mysql-test
          image: rmazumde123/docker-mysql:1.0
          ports:
            - containerPort: 8084
          imagePullPolicy: Never
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value : mysql

            - name: DB_NAME  # Setting Database name from configMap
              value: testdb

            - name: DB_USERNAME  # Setting Database username from Secret
              value: rintu

            - name: DB_PASSWORD # Setting Database password from Secret
              value: rintu

          

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: docker-mysql-svc
spec:
  selector:
    app: docker-mysql
  ports:
    - protocol: "TCP"
      port: 8084 # The port that the service is running on in the cluster
      targetPort: 8084 # The port exposed by the service
  type: LoadBalancer # type of the service.

